const cardobject = [
  {
    id: 0,
    title: 'Malibu',
    price: 35000,
    comment: 20,
    like: 12,
    position: false,
    imgurl: './images/malibu.jpg',
  },
  {
    id: 1,
    title: 'Damas',
    price: 7500,
    comment: 200,
    like: 1,
    position: false,
    imgurl: './images/damas.jpg',
  },
  {
    id: 9,
    title: 'Trailblazer',
    price: 38000,
    comment: 13,
    like: 21,
    position: false,
    imgurl: './images/trailblazer.png',
  },
  {
    id: 2,
    title: 'Nexia 3',
    price: 76000,
    comment: 37,
    like: 11,
    position: false,
    imgurl: './images/nexia.jpg',
  },
  {
    id: 3,
    title: 'Damas Labo',
    price: 7700,
    comment: 0,
    like: 0,
    position: false,
    imgurl: './images/labo.jpg',
  },

  {
    id: 7,
    title: 'Tahoe',
    price: 75000,
    comment: 9,
    like: 1,
    position: false,
    imgurl: './images/tahoe.jpg',
  },
  {
    id: 4,
    title: 'Cobalt',
    price: 9500,
    comment: 27,
    like: 10,
    position: false,
    imgurl: './images/cobalt.jpg',
  },
  {
    id: 5,
    title: 'Gentra',
    price: 1100,
    comment: 7,
    like: 17,
    position: false,
    imgurl: './images/gentra.jpg',
  },
  {
    id: 11,
    title: 'Malibu',
    price: 35000,
    comment: 20,
    like: 12,
    position: false,
    imgurl: './images/malibu.jpg',
  },
  {
    id: 6,
    title: 'Spark',
    price: 7200,
    comment: 9,
    like: 171,
    position: true,
    imgurl: './images/spark.jpg',
  },

  {
    id: 8,
    title: 'Tracker',
    price: 22000,
    comment: 53,
    like: 8,
    position: false,
    imgurl: './images/tracker.jpg',
  },
  {
    id: 10,
    title: 'Trailblazer',
    price: 38000,
    comment: 13,
    like: 21,
    position: false,
    imgurl: './images/trailblazer.png',
  },
];

export const getCardObject = () => {
  return [...cardobject];
};
